### ISSUE TITLE
Protecting front end registration forms.

### ISSUE THREAD

**Issue by fantasticmachine** [barrelstrength/craft-sprout-invisible-captcha#4]
I'm using this on a Craft 2 site.
I’ve flicked the switch to have it automatically protect front end registration forms but I don’t see anything in the form to indicate it’s being protected. Do I need to add anything to the markup?

**Comment by BenParizek** [comment]
@fantasticmachine You'll need to add this line within your `<form>` tags: 

```
{{ craft.sproutInvisibleCaptcha.protect() }}
```
