### ISSUE TITLE
Error 'OnBeforeSaveEntryEvent' with Sproutforms

### ISSUE THREAD

**Issue by SamLNL** [barrelstrength/craft-sprout-invisible-captcha#5]
Hello,

Submitting a form with Sproutforms (https://github.com/barrelstrength/craft-sprout-forms) works like a charm. But whenever I try to submit a form with this plugin `craft-sprout-invisible-captcha` activated, Sproutforms will give me the following error: 

```
2019/07/19 08:14:49 [error] [plugin] OnBeforeSaveEntryEvent is not valid
2019/07/19 08:14:49 [error] [plugin] [Forced] Unable to save form entry. Errors: []
```

Even with all the options (available in CMS) unchecked for the `craft-sprout-invisible-captcha` plugin, it will give me this error.

I'm connecting `craft-sprout-invisible-captcha` with `craft-sprout-forms` by using  `{{ craft.sproutInvisibleCaptcha.protect() }}` in my form template. But that doesn't seem to be the problem. Even deleting this line of code, will trigger the same error.

Sproutforms version: 2.6.4  
Sprout Invisible Captcha version: 0.9.1  
Sprout Fields version: 2.2.0
Sprout Reports version: 0.10.3

Craft version: 2.7.9

**Comment by andrelopez** [comment]
Hi @SamLNL Sorry for the late reply. We're unable to recreate this issue. Have you still having this issue? If so could you please recreate the issue and send back to us the following files to support@barrelstrengthdesign.com?

craft/storage/runtime/logs/sproutinvisiblecaptcha.log and craft/storage/runtime/logs/sproutforms.log

Best,

**Comment by SamLNL** [comment]
I'm not using this plugin anymore, I used Google ReCaptcha instead. I couldn't get it to work. Unfortunately I don't have the logs anymore. Sorry.
